sort_by = "position"
separator_string = "ó°§Ÿ"  # nf-md-circle_small

overflow_fg_color = "#e8c580"

[window_nicknames]
"TelegramDesktop"           = "telegram"
"discord-stable"            = "discord"
"firefox-developer-edition" = "firefox-dev"
"ardour-8.12.0"             = "ardour"
