sort_by = "position"
separator_string = "ó°§Ÿ"  # nf-md-circle_small

inactive_window_fg_color = "#888888"
separator_fg_color       = "#888888"
overflow_fg_color        = "#e8c580"

[window_nicknames]
"TelegramDesktop"           = "telegram"
"firefox-developer-edition" = "firefox-dev"
"ardour-8.12.0"             = "ardour"
